# permissions for end users to view resourcerefs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: resourceref-viewer-role
rules:
- apiGroups:
  - samze.samze.com
  resources:
  - resourcerefs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - samze.samze.com
  resources:
  - resourcerefs/status
  verbs:
  - get
