
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - samze.samze.com
  resources:
  - resourcerefs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - samze.samze.com
  resources:
  - resourcerefs/finalizers
  verbs:
  - update
- apiGroups:
  - samze.samze.com
  resources:
  - resourcerefs/status
  verbs:
  - get
  - patch
  - update
